FROM ghcr.io/graalvm/native-image-community:23 AS build

WORKDIR /usr/src/app

COPY . .
RUN ./mvnw.sh clean install dependency:go-offline -DskipTests -pl shared -pl generation-task
RUN ./mvnw.sh native:compile -Pnative -DskipTests dependency:go-offline -pl shared -pl generation-task


FROM debian:bookworm-slim

WORKDIR /app

# Copy the native binary from the build stage
COPY --from=build /usr/src/app/generation-task/target/generation-task /app/task

# Run the application
CMD ["/app/task"]