FROM ghcr.io/graalvm/native-image-community:23 AS build

WORKDIR /usr/src/app

COPY . .
RUN ./mvnw.sh clean install -U -pl shared -pl pokemon-task -DskipTests
RUN ./mvnw.sh native:compile -Pnative -DskipTests -pl shared -pl pokemon-task


FROM debian:bookworm-slim

WORKDIR /app

# Copy the native binary from the build stage
COPY --from=build /usr/src/app/pokemon-task/target/pokemon-task /app/pokemon-task

# Run the application
CMD ["/app/pokemon-task"]