# External access for the k8s cluster to Redis
# redis-external-service.pokedex.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: redis-external-service
  namespace: pokedex
spec:
  type: ExternalName
  externalName: "host.minikube.internal"
---
# External access for the k8s cluster to MongoDb
# mongodb-external-service.pokedex.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: mongodb-external-service
  namespace: pokedex
spec:
  type: ExternalName
  externalName: "host.minikube.internal"
---