# Spring
spring:
  grpc:
    server:
      keep-alive:
      port: 9090
      host: "*"
  main:
    web-application-type: none
  application:
    name: "redis-bouncer"
  data:
    redis:
      client-type: lettuce
      host: "localhost"
      port: 6379
      lettuce:
        pool:
          enabled: true
          time-between-eviction-runs: 60s
          max-wait: -1ms
          min-idle: 3
          max-idle: 8
          max-active: 20