# Spring
spring:
  application:
    name: "redis-bouncer"
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 9090
      host: "*"
      reflection:
        enabled: false
  data:
    redis:
      client-type: lettuce
      host: "localhost"
      port: 6379
      lettuce:
        pool:
          enabled: true
          time-between-eviction-runs: 60s
          max-wait: -1ms
          min-idle: 0
          max-idle: -1
          max-active: -1