# Spring
spring:
  application:
    name: "generation-task"
  main:
    web-application-type: none
    lazy-initialization: true
  grpc:
    client:
      channels:
        redis-bouncer:
          address: "0.0.0.0:9090"