# Spring
spring:
  main:
    web-application-type: none
  application:
    name: "generation-task"
  data:
    redis:
      client-name: "generation-task"
      host: "localhost"
      port: 6379
      client-type: lettuce