# Spring
spring:
  application:
    name: "generation-task"
  main:
    web-application-type: none
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      repositories:
        type: none
  grpc:
    client:
      channels:
        redis-bouncer:
          address: "static://0.0.0.0:9000"