# Spring
spring:
  application:
    name: "pokemon-task"
  main:
    web-application-type: none
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      channels:
        mongodb-bouncer:
          address: "static://0.0.0.0:9090"
        redis-bouncer:
          address: "static://0.0.0.0:9000"