# Spring
spring:
  main:
    web-application-type: none
    lazy-initialization: true
  application:
    name: "pokemon-task"
  grpc:
    client:
      channels:
        redis-bouncer:
          address: "static://0.0.0.0:9090"
  threads:
    virtual:
      enabled: true