# Spring
spring:
  main:
    web-application-type: none
  application:
    name: "pokemon-task"
  data:
    redis:
      client-name: "pokemon-task"
      host: "localhost" # "host.docker.internal"
      port: 6379
      client-type: lettuce