# Application properties
app:
  task:
    name-stream-key: pokemon_name_event
    media-stream-key: pokemon_media_event
# Spring
spring:
  application:
    name: "pokemon-task"
  main:
    web-application-type: none
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  grpc:
    client:
      channels:
        pokeapi-bouncer:
          max-inbound-metadata-size: 15000B
          address: "static://0.0.0.0:9000"
        redis-bouncer:
          address: "static://0.0.0.0:9010"
        mongodb-bouncer:
          address: "static://0.0.0.0:9020"