apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-bouncer-config
  namespace: pokedex
data:
  SPRING_DATA_REDIS_HOST: "redis-external-service.pokedex.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_GRPC_SERVER_PORT: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-bouncer-service
  namespace: pokedex
spec:
  selector:
    app: redis-bouncer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-bouncer
  namespace: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-bouncer-app
  template:
    metadata:
      labels:
        app: redis-bouncer-app
    spec:
      containers:
        - name: redis-bouncer-container
          image: pokedex-redis-bouncer:latest
          imagePullPolicy: Never
          ports:
            - protocol: "TCP"
              containerPort: 80
          envFrom:
            - configMapRef:
                name: redis-bouncer-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"