# Server
server:
  port: 8081

# Spring
spring:
  data:
    mongodb:
      uri: "mongodb://admin:password@localhost:27017"
      database: "pokemon-db"
      gridfs:
        bucket: "pokemon"
        database: "pokemon-db"