app:
  file-server:
    scheme: "http"
    host: "localhost"
    port: 8081
    uri: "api/v1/file/{fileName}"

# Spring
spring:
  application:
    name: scheduler
  main:
    keep-alive: true
    web-application-type: none
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
  data:
    redis:
      client-name: "scheduler"
      host: "localhost"
      port: 6379
      client-type: jedis
      connect-timeout: 30
      jedis:
        pool:
          enabled: true
          max-active: 20
          max-idle: -1
          max-wait: 30s
          min-idle: 5
          time-between-eviction-runs: 60m
    mongodb:
      uri: "mongodb://admin:password@localhost:27017"
      database: "pokemon-db"
      gridfs:
        bucket: "pokemon"
        database: "pokemon-db"
      auto-index-creation: true
