# Spring
spring:
  application:
    name: scheduler
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
  data:
    redis:
      client-name: "scheduler"
      host: "localhost"
      port: 6379
