// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: image_converter.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConvertImage_Convert_FullMethodName = "/ConvertImage/Convert"
)

// ConvertImageClient is the client API for ConvertImage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MongoDb GRPC Operations
type ConvertImageClient interface {
	// Insert one entry
	Convert(ctx context.Context, in *HelloWorld, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type convertImageClient struct {
	cc grpc.ClientConnInterface
}

func NewConvertImageClient(cc grpc.ClientConnInterface) ConvertImageClient {
	return &convertImageClient{cc}
}

func (c *convertImageClient) Convert(ctx context.Context, in *HelloWorld, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, ConvertImage_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConvertImageServer is the server API for ConvertImage service.
// All implementations must embed UnimplementedConvertImageServer
// for forward compatibility.
//
// MongoDb GRPC Operations
type ConvertImageServer interface {
	// Insert one entry
	Convert(context.Context, *HelloWorld) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedConvertImageServer()
}

// UnimplementedConvertImageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConvertImageServer struct{}

func (UnimplementedConvertImageServer) Convert(context.Context, *HelloWorld) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedConvertImageServer) mustEmbedUnimplementedConvertImageServer() {}
func (UnimplementedConvertImageServer) testEmbeddedByValue()                      {}

// UnsafeConvertImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConvertImageServer will
// result in compilation errors.
type UnsafeConvertImageServer interface {
	mustEmbedUnimplementedConvertImageServer()
}

func RegisterConvertImageServer(s grpc.ServiceRegistrar, srv ConvertImageServer) {
	// If the following call pancis, it indicates UnimplementedConvertImageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConvertImage_ServiceDesc, srv)
}

func _ConvertImage_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorld)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConvertImageServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConvertImage_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConvertImageServer).Convert(ctx, req.(*HelloWorld))
	}
	return interceptor(ctx, in, info, handler)
}

// ConvertImage_ServiceDesc is the grpc.ServiceDesc for ConvertImage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConvertImage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ConvertImage",
	HandlerType: (*ConvertImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _ConvertImage_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image_converter.proto",
}
