# Spring
spring:
  application:
    name: "mongodb-bouncer"
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 9020
      host: "*"
      reflection:
        enabled: false
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      username: "admin"
      password: "password"
      authentication-database: "admin"
      database: "pokemon"
      gridfs:
        bucket: "pokemon"
        database: "pokemon"
      auto-index-creation: true