apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-bouncer-config
  namespace: pokedex
data:
  SPRING_DATA_MONGODB_HOST: "mongodb-external.pokedex.svc.cluster.local"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_GRPC_SERVER_PORT: "80"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-bouncer-secret
  namespace: pokedex
type: Opaque
data:
  # admin
  SPRING_DATA_MONGODB_USERNAME: "YWRtaW4="
  # password
  SPRING_DATA_MONGODB_PASSWORD: "cGFzc3dvcmQ="
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-bouncer-service
  namespace: pokedex
spec:
  selector:
    app: mongodb-bouncer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-bouncer
  namespace: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-bouncer-app
  template:
    metadata:
      labels:
        app: mongodb-bouncer-app
    spec:
      containers:
        - name: mongodb-bouncer-container
          image: pokedex-mongodb-bouncer:latest
          imagePullPolicy: Never
          ports:
            - protocol: "TCP"
              containerPort: 80
          envFrom:
            - secretRef:
                name: graphql-api-secret
            - configMapRef:
                name: graphql-api-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"