# Server
server:
  port: 8080

# Spring
spring:
  application:
    name: graphql-server
  graphql:
    schema:
      file-extensions: .graphql
    graphiql:
      enabled: true
      path: "/graphiql"
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
      allowed-methods: "*"
    path: "/api/v1/graphql"
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      username: "admin"
      password: "password"
      authentication-database: "admin"
      database: "pokemon"
      auto-index-creation: true