# Server
server:
  port: 8080

# Spring
spring:
  application:
    name: graphql-server
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
    cors:
      allowed-origins: "*"
      allowed-headers: "*"
      allowed-methods: "*"
    path: "api/v1/graphql"