# Spring
spring:
  application:
    name: "pokeapi-bouncer"
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true
  grpc:
    server:
      port: 9000
      host: "*"
      reflection:
        enabled: false
    client:
      channels:
        redis-bouncer:
          address: "static://0.0.0.0:9010"