apiVersion: v1
kind: ConfigMap
metadata:
  name: image-converter-config
  namespace: pokedex
data:
  PORT: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: image-converter-service
  namespace: pokedex
spec:
  selector:
    app: image-converter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-converter
  namespace: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-converter-app
  template:
    metadata:
      labels:
        app: image-converter-app
    spec:
      containers:
        - name: image-converter-container
          image: pokedex-image-converter:latest
          imagePullPolicy: Never
          ports:
            - protocol: "TCP"
              containerPort: 80
          envFrom:
            - configMapRef:
                name: image-converter-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"