# redis.pokedex.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pokedex
  labels:
    app: pokedex
    tier: cache
  annotations:
    description: "External Redis cache service running on host machine"
spec:
  type: ExternalName
  externalName: "host.minikube.internal"
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
# mongodb.pokedex.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: pokedex
  labels:
    app: pokedex
    tier: database
  annotations:
    description: "External MongoDb instance running on host machine"
spec:
  type: ExternalName
  externalName: "host.minikube.internal"
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017