# Application properties
app:
  scheduler:
    enabled: true
# Spring Properties
spring:
  application:
    name: "pokedex-scheduler"
  main:
    web-application-type: none
    keep-alive: true
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      pool:
        size: 10
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      username: "admin"
      password: "password"
      authentication-database: "admin"
      database: "pokemon"
      gridfs:
        bucket: "pokemon"
        database: "pokemon"
      auto-index-creation: true
    redis:
      client-type: lettuce
      host: "localhost"
      port: 6379
      lettuce:
        pool:
          enabled: true
          time-between-eviction-runs: 60s
          max-wait: -1ms
          min-idle: 0
          max-idle: -1
          max-active: -1
# Logging properties
logging:
  level:
    root: info
    com.github.mangila.pokedex: debug
    web: debug