# Create NodePort service for Graphql Api
apiVersion: v1
kind: Service
metadata:
  name: graphql-api
  namespace: pokedex
spec:
  selector:
    app: graphql-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Pod