apiVersion: v1
kind: ConfigMap
metadata:
  name: media-task-config
  namespace: pokedex
data:
  SPRING_GRPC_CLIENT_CHANNELS_REDIS-BOUNCER_ADDRESS: "static://redis-bouncer-service"
  SPRING_GRPC_CLIENT_CHANNELS_IMAGE-CONVERTER_ADDRESS: "static://image-converter-service"
  SPRING_GRPC_CLIENT_CHANNELS_MONGODB-BOUNCER_ADDRESS: "static://mongodb-bouncer-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-dead-task-config
  namespace: pokedex
data:
  APP_TASK_MEDIA-STREAM-KEY: "pokemon_media_dead_event"
  SPRING_GRPC_CLIENT_CHANNELS_REDIS-BOUNCER_ADDRESS: "static://redis-bouncer-service"
  SPRING_GRPC_CLIENT_CHANNELS_IMAGE-CONVERTER_ADDRESS: "static://image-converter-service"
  SPRING_GRPC_CLIENT_CHANNELS_MONGODB-BOUNCER_ADDRESS: "static://mongodb-bouncer-service"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: media-task-cronjob
  namespace: pokedex
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      parallelism: 10
      completions: 10
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: media-task-container
              image: pokedex-media-task
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: media-task-config
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: media-dead-task-cronjob
  namespace: pokedex
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: media-task-container
              image: pokedex-media-task
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: media-dead-task-config
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"