apiVersion: v1
kind: ConfigMap
metadata:
  name: pokeapi-bouncer-config
  namespace: pokedex
data:
  SPRING_GRPC_CLIENT_CHANNELS_REDIS-BOUNCER_ADDRESS: "static://redis-bouncer-service"
  SPRING_GRPC_SERVER_PORT: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: pokeapi-bouncer-service
  namespace: pokedex
spec:
  selector:
    app: pokeapi-bouncer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-bouncer
  namespace: pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi-bouncer-app
  template:
    metadata:
      labels:
        app: pokeapi-bouncer-app
    spec:
      containers:
        - name: pokeapi-bouncer-container
          image: pokedex-pokeapi-bouncer:latest
          imagePullPolicy: Never
          ports:
            - protocol: "TCP"
              containerPort: 80
          envFrom:
            - configMapRef:
                name: pokeapi-bouncer-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"